#######################################################
# 
# CambioEstado.py
# Python implementation of the Class CambioEstado
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################
import Estado
import datetime
import random

class CambioEstado:
    
    def __init__(self, fechaHoraInicio, estado):
        self.fechaHoraInicio = fechaHoraInicio
        self.estado = estado

    def esEstadoInicial(self):
        if self.estado == 'Iniciada':
            return True

    def esUltimoEstado(self):
        pass

    def getFechaHoraInicio(self):
        return self.fechaHoraInicio

    def getNombreEstado(self):
        return self.estado.getNombre() 

    def new(self):
        pass


def obtenerFechaRandom():
    anio_aleatorio = random.randint(1900, 2023)
    mes_aleatorio = random.randint(1, 12)
    dia_aleatorio = random.randint(1, 30)
    hora_aleatoria = random.randint(0, 23)
    minuto_aleatorio = random.randint(0, 59)
    segundo_aleatorio = random.randint(0, 59)

    estado1 = Estado.obtenerEstado()

    fechaRandom = datetime.datetime(anio_aleatorio, mes_aleatorio, dia_aleatorio, hora_aleatoria, minuto_aleatorio, segundo_aleatorio)
    cambioEstado1 = CambioEstado(fechaRandom, estado1)
    return cambioEstado1