#######################################################
# 
# Cliente.py
# Python implementation of the Class Cliente
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################
import random

class Cliente:
    def __init__(self,dni,nombre_apellido,nrocelular):
        self.dni = dni
        self.nombre_apellido = nombre_apellido
        self.nrocelular = nrocelular

    def esCliente(self):
        return True

    def getNombre(self):
        return self.nombre_apellido
    
    def __str__(self):
        r = ''
        r += '{:<30}'.format("DNI: " + str(self.dni))
        r += '{:<30}'.format("Nombre y Apellido: " + self.nombre_apellido)
        r += '{:<30}'.format("numero: " + str(self.nrocelular))
        return r


class adhoc:
    def crearCliente(n):
        desc_nombres = ["Juan","Joaquin","Fabrizio", "Luciana","Matias","Mateo","Federico","Santiago","Lucia","Valentina","Victoria", "Ana", "María","Pedro","Josefina","Jose","Lucio","Patricia","Natalia"]
        desc_apellidos = ["Sposetti","Gonzalez", "Rodriguez", "Lopez", "Martinez", "Perez", "Gomez", "Sanchez", "Fernandez", "Torres", "Ramirez", "Hernandez", "Garcia", "Silva", "Rojas", "Moreno", "Navarro", "Cruz", "Ortega", "Vargas", "Mendoza"]
        vec_clientes = []
        for i in range(n):
            dni = random.randint(100000, 46000000)
            nombre_apellido = random.choice(desc_nombres) + " " +random.choice(desc_apellidos)
            nrocelular = random.randint(540000000000, 550000000000)
            cliente = Cliente(dni,nombre_apellido, nrocelular)
            vec_clientes.append(cliente)
        return vec_clientes


def main():
    clientes = adhoc.crearCliente(10)
    print(clientes[1])
    print(clientes[1].getNombre())


if __name__ == "__main__":
    main()