#######################################################
# 
# Cliente.py
# Python implementation of the Class Cliente
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################
import random

class Cliente:
    def _init_(self,dni,nombre_apellido,nrocelular):
        self.dni = dni
        self.nombre_apellido = nombre_apellido
        self.nrocelular = nrocelular

    def esCliente(self):
        return True

    def getNombre(self):
        return self.nombre_apellido


def crearCliente(n):
        desc_nombres = ["Juan","Joaquin","Fabrizio", "Luciana","Matias","Mateo","Federico","Santiago","Lucia","Valentina","Victoria", "Ana", "María","Pedro","Josefina","Jose","Lucio","Patricia","Natalia"]
        desc_apellidos = ["Sposetti","Gonzalez", "Rodriguez", "Lopez", "Martinez", "Perez", "Gomez", "Sanchez", "Fernandez", "Torres", "Ramirez", "Hernandez", "Garcia", "Silva", "Rojas", "Moreno", "Navarro", "Cruz", "Ortega", "Vargas", "Mendoza"]
        vec_clientes = []
        for i in range(n):
            dni = random.randint(100000, 46000000)
            nombre_apellido = random.choice(desc_nombres) + " " +random.choice(desc_apellidos)
            nrocelular = random.randint(540000000000, 550000000000)
            cliente = Cliente(dni,nombre_apellido, nrocelular)
            vec_clientes.append(cliente)
        return vec_clientes

def to_string(cliente):
    cadena = "DNI: " + str(cliente.dni) + "\t" \
             "nom y apellido: " + cliente.nombre_apellido + "\t" \
             "numero: " + str(cliente.nrocelular) + "\t" 
    return cadena

def mostrar_cliente(vector):
    cadena = "cliente \n"
    cadena += "=" * 80 + "\n"
    for cliente in vector:
        cadena += to_string(cliente) + "\n"
    print(cadena)