#######################################################
# 
# Encuesta.py
# Python implementation of the Class Encuesta
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################
import Pregunta

class Encuesta:
    m_Pregunta= Pregunta()

    def armarEncuesta():
        pass

    def esEncuestaDeCliente():
        pass

    def esVigente():
        pass

    def getDescripcionEncuesta():
        pass