#######################################################
# 
# Estado.py
# Python implementation of the Class Estado
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################


class Estado:
    def esFinalizada():
        pass

    def esIniciada():
        pass

    def getNombre():
        pass