#######################################################
# 
# Estado.py
# Python implementation of the Class Estado
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################
import random

class Estado:
    def __init__(self, nombre):
        self.nombre = nombre

    def esFinalizada(self):
        if self.nombre == 'Finalizada':
            return True
        return False

    def esIniciada(self):
        if self.nombre == 'Iniciada':
            return True
        return False
    
    def getNombre(self):
        return self.nombre

class adhoc:
    def obtenerEstado():
        arrayEstados = ['Iniciada', 'En Curso', 'Finalizada', 'Cancelada']
        nombre = random.choice(arrayEstados)
        estado1 = Estado(nombre)
        return estado1

    def __str__(self):
        r = ''
        r += '{:<30}'.format("Nombre Estado: " + str(self.nombre))
        return r
