#######################################################
# 
# GestorConsultarEncuesta.py
# Python implementation of the Class GestorConsultarEncuesta
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################


class GestorConsultarEncuesta:
    def nuevaConsultaEncuesta():
        pass

    def tomarPeriodo():
        pass

    def buscarLlamadas():
        pass

    def tomarSeleccionLlamada():
        pass

    def buscarDatosRtas():
        pass

    def tomarSeleccionSalida():
        pass

    def finCU():
        pass

    def generarCsv():
        pass