#######################################################
# 
# GestorConsultarEncuesta.py
# Python implementation of the Class GestorConsultarEncuesta
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################

from datetime import datetime

class GestorConsultarEncuesta:
    def __init__(self, 
    pantallaConsultarEncuesta = None, 
    llamadas = [],
    fechaInicioPeriodo = datetime.now(), 
    fechaFinPeriodo = datetime.now()):
        self.pantalla = pantallaConsultarEncuesta
        self.llamadas = llamadas
        self.fechaInicioPeriodo = fechaInicioPeriodo
        self.fechaFinPeriodo = fechaFinPeriodo

    def nuevaConsultaEncuesta(self):
        self.pantalla.pedirPeriodo()

    def tomarPeriodo(self, fechaInicio, fechaFin):
        self.fechaInicioPeriodo = fechaInicio
        self.fechaFinPeriodo = fechaFin
        self.buscarLlamadas()

    def buscarLlamadas(self):
        pass

    def tomarSeleccionLlamada(self):
        pass

    def buscarDatosRtas(self):
        pass

    def tomarSeleccionSalida(self):
        pass

    def finCU(self):
        pass

    def generarCsv(self):
        pass