#######################################################
# 
# Llamada.py
# Python implementation of the Class Llamada
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################
import RespuestaDeCliente
import CambioEstado
import Cliente

class Llamada:
    m_RespuestaDeCliente= RespuestaDeCliente()

    m_CambioEstado= CambioEstado()

    m_Cliente= Cliente()

    def calcularDuracion():
        pass

    def esDePeriodo():
        pass

    def getDuracion():
        pass

    def getNombreClienteDeLlamada():
        pass

    def new():
        pass

    def getRespuestas():
        pass

    def setDescripcionOperador():
        pass

    def setDuracion():
        pass

    def setEstadoActual():
        pass

    def tieneRta():
        pass

    def getLlamada():
        pass

    def getEstadoActual():
        pass