#######################################################
# 
# PantallaConsultarEncuesta.py
# Python implementation of the Class PantallaConsultarEncuesta
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################

import PySimpleGUI as GUI

class PantallaConsultarEncuesta:
    def __init__(self, gestorConsultarEncuesta = None, 
    txtFechaInicio = GUI.InputText('Fecha Inicio: ', disabled = True, key='txtFI'), 
    calendarBtnFechaInicio = GUI.CalendarButton(button_text='Seleccionar Inicio', key='BtnFI', target='txtFI', format='%d/%m/%Y'),
    txtFechaFin = GUI.InputText('Fecha Fin: ', disabled = True, key='txtFF'),
    calendarBtnFechaFin = GUI.CalendarButton(button_text='Seleccionar Fin', key='BtnFI', target='txtFF', format='%d/%m/%Y'),
    btnCancel = GUI.Cancel()):
        self.gestor = gestorConsultarEncuesta
        self.txtFechaInicio = txtFechaInicio
        self.txtFechaFin = txtFechaFin
        self.calendarBtnFechaInicio = calendarBtnFechaInicio
        self.calendarBtnFechaFin = calendarBtnFechaFin
        self.btnCancel = btnCancel

    def opcionConsultarEncuesta(self, gestor):
        self.gestor = gestor
        self.habilitarVentana()

    def habilitarVentana(self):
        col1 = GUI.Column([[self.txtFechaInicio], [self.txtFechaFin]])
        col2 = GUI.Column([[self.calendarBtnFechaInicio], [self.calendarBtnFechaFin]])
        layout = [
            [col1, col2],
            [self.btnCancel]
        ]
        window = GUI.Window('Consultar Encuesta', layout, resizable=False)
        while True:
            event, values = window.read()

            if event == GUI.WIN_CLOSED or event == 'Cancel':
                break
            

        window.close()

    def pedirPeriodo():
        pass

    def tomarPeriodo():
        pass

    def pedirSeleccionLlamada():
        pass

    def tomarSeleccionLlamada():
        pass

    def pedirSeleccionSalida():
        pass

    def tomarSeleccionSalida():
        pass