#######################################################
# 
# PantallaConsultarEncuesta.py
# Python implementation of the Class PantallaConsultarEncuesta
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################


class PantallaConsultarEncuesta:
    def opcionConsultarEncuesta():
        pass

    def habilitarVentana():
        pass

    def pedirPeriodo():
        pass

    def tomarPeriodo():
        pass

    def pedirSeleccionLlamada():
        pass

    def tomarSeleccionLlamada():
        pass

    def pedirSeleccionSalida():
        pass

    def tomarSeleccionSalida():
        pass