#######################################################
# 
# Pregunta.py
# Python implementation of the Class Pregunta
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################
import RespuestaPosible

class Pregunta:
    m_RespuestaPosible= RespuestaPosible()

    def getDescripcion():
        pass

    def listarRespuestasPosibles():
        pass