#######################################################
# 
# Pregunta.py
# Python implementation of the Class Pregunta
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################
import RespuestaPosible

class Pregunta:
<<<<<<< HEAD
    m_RespuestaPosible= RespuestaPosible()
=======
    def __init__(self, preg='', resp=RespuestaPosible()):
        self.pregunta = preg
        self.m_respuestaPosible = resp
>>>>>>> 88083ac7c46166c3251282e1eca0989aa58e69d0

    def getDescripcion():
        pass

    def listarRespuestasPosibles():
<<<<<<< HEAD
        pass
=======
        pass

preguntasRandom = {
    1: ['¿Le gustó la atención?', [self.m_respuestaPosible[0], self.m_respuestaPosible[1]]],
    2: ['¿Del 1 al 10 en cuánto nos calificaría?', []],
    3: ['¿Nos recomendaría a otras personas?', []]
}


def generarPreguntasAleatorias(cantidadPreguntas):
    for i in range(cantidadPreguntas):
        preguntas[i] = Pregunta()
        preguntas[i].pregunta = preguntasRandom[i]
        preguntas[i].m_respuestaPosible = RespuestaPosible.generarRespuestaPosibleAleatoria(cantidadPreguntas)
    
    print('Preguntas generadas con exito')
>>>>>>> 88083ac7c46166c3251282e1eca0989aa58e69d0
