#######################################################
# 
# RespuestaPosible.py
# Python implementation of the Class RespuestaPosible
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################


class RespuestaPosible:
    def getDescripcionRta():
        pass