#######################################################
# 
# RespuestaDeCliente.py
# Python implementation of the Class RespuestaDeCliente
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################
import RespuestaPosible

class RespuestaDeCliente:
    def __init__(self, fechaEncuesta='', respuestaSeleccionada=None):
        self.fechaEncuesta = feEnc
        self.m_respuestaSeleccionada = rtaSel

    def getDescripcionRta():
        return self.descripcion


