#######################################################
# 
# RespuestaDeCliente.py
# Python implementation of the Class RespuestaDeCliente
# Generated by Enterprise Architect
# Created on:      11-may.-2023 16:25:04
# Original author: usuario
# 
#######################################################
import RespuestaPosible

class RespuestaDeCliente:
    m_RespuestaPosible= RespuestaPosible()

    def getDescripcionRta():
        pass